# Generated by Django 3.0.10 on 2024-07-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='email', max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='first_name',
            field=models.CharField(default='some string', max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(default='some string', max_length=200),
        ),
    ]
