# Generated by Django 3.0.10 on 2024-07-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobs_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
