# Generated by Django 3.0.10 on 2024-07-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20240720_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_name',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
