# Generated by Django 3.0.10 on 2024-07-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20240720_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/'),
        ),
    ]
