# Generated by Django 3.0.10 on 2024-07-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20240720_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='requirements',
            field=models.TextField(default=' ', max_length=200),
        ),
    ]
